# -*- coding: utf-8 -*-
"""neural network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19e6k1zYXrPjK2AVfyXeTvMMPdd0V6f88
"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

