# -*- coding: utf-8 -*-
"""NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19e6k1zYXrPjK2AVfyXeTvMMPdd0V6f88
"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

X=torch.tensor([[0.,0.],[0.,1],[1.,0.],[1.,1.]])
y=torch.tensor([[0.],[1.],[1.],[0.]])

loss_fn=nn.MSELoss()
opt=torch.optim.Adam(model.parameters(), lr=0.01)

for _ in range(1000):
  opt.zero_grad()
  loss =loss_fn(model(X), y)
  loss.backward()
  opt.step()

"""**Model inference**

We print the model's predictions after training.
"""

print(model(X))

!pip install google.genai

from google import genai

from google import genai
client = genai.Client(api_key='AIzaSyBzRIUPQCft6KmzuOyta_YxELIqQ0sFcKA')

response=client.models.generate_content(
    model='gemini-2.5-flash',
    contents='Why is the sky blue?'
).text
print(response)